on:
  workflow_dispatch:
  release:
    types: [published]
name: Deploy Glyphr Studio App
jobs:
  web-deploy:
    name: 🚀 Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        protocol: ftps
        port: 22
        local-dir: ./dist/
        server: ${{ secrets.SSH_SERVER_NAME }}
        #remote-user: ${{ secrets.SSH_USERNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        #private-ssh-key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.SSH_KEY }}
        server-dir: ${{ secrets.APP_DIRECTORY }}        
        # rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
        dry-run: true
